/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jadson' at '12/02/16 10:48' with Gradle 2.10
 *
 * @author jadson, @date 12/02/16 10:48
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
